### ISSUE TITLE
Cursive stub generation problem:  cyclic dependencies

### ISSUE THREAD

**Issue by markaddleman** [fulcrologic/fulcro#127]
I created a new fulcro project using `lein new fulcro app nodemo`.  Cursive tries to create stubs but reports a cyclic dependency exception between /fulcro/server and /fulcro/easy_server.  

Full stack track:
```
7:18 AM	Error generating stubs for module fulcro: Exception in thread "main" java.lang.ExceptionInInitializerError
				at clojure.main.<clinit>(main.java:20)
				Caused by: java.lang.Exception: Cyclic load dependency: [ /fulcro/server ]->/fulcro/easy_server->[ /fulcro/server ]->/fulcro_spec/runner->/fulcro_spec/suite, compiling:(fulcro/easy_server.clj:1:1)
				at clojure.core$throw_if.invokeStatic(core.clj:5807)
				at clojure.core$check_cyclic_dependency.invokeStatic(core.clj:5939)
				at clojure.core$load.invokeStatic(core.clj:6040)
				at clojure.core$load.doInvoke(core.clj:6029)
				at clojure.lang.RestFn.invoke(RestFn.java:408)
				at clojure.core$load_one.invokeStatic(core.clj:5848)
				at clojure.core$load_one.invoke(core.clj:5843)
				at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
				at clojure.core$load_lib.invokeStatic(core.clj:5887)
				at clojure.core$load_lib.doInvoke(core.clj:5868)
				at clojure.lang.RestFn.applyTo(RestFn.java:142)
				at clojure.core$apply.invokeStatic(core.clj:659)
				at clojure.core$load_libs.invokeStatic(core.clj:5925)
				at clojure.core$load_li... (show balloon)
```

**Comment by awkay** [comment]
Surprising....I'll have a look

**Comment by awkay** [comment]
So, make sure you're up to date on versions, and try Invalidate Caches and Restart in IntelliJ. I'm unable to reproduce this. I'm going to manually look into the cyclic message and see if I can see something, but so far nothing.

**Comment by markaddleman** [comment]
I'll take a look later today.  I should have updated the issue to say that I got a similar problem with `lein repl`  I'll post my project.clj later today.

**Comment by markaddleman** [comment]
Sorry for the false alarm - I can't reproduce
